#!/bin/bash
#--------------------------------------------------------------------------
# Blacklist : Deny all connection from an ip/network
#
# patterns :
# 	Blacklist <ip/network>[,<ip/network>[,...]]
#
# examples :
#	Blacklist host.domain.tld
#	Blacklist 5.6.7.8
#	Blacklist 3.4.5.0/24
#	Blacklist host.domain.tld,55.6.7.8,3.4.5.0/24
#--------------------------------------------------------------------------
function Blacklist {

	for i in $(echo $1 | sed 's/,/ /g')
	do
		fw-addDescription $PRIO_BLACKLIST [input][$i]=DROP
	done

	fw-addRule $PRIO_BLACKLIST $IPTABLES -I INPUT -j DROP -s $1
}
