#!/bin/bash
#--------------------------------------------------------------------------
# Pingable : Allow ICMP ping requests
#
# patterns :
#	Pingable always
#
#	Pingable from <ip/network>
#		from = ip or network of authorized peer
#
#	Pingable via <interface>
#		via = interface authorized to receive ping
#
# examples :
#	Pingable always
#	Pingable from 5.6.7.8
# 	Pingable from 3.4.5.6/24
# 	Pingable via eth0
#--------------------------------------------------------------------------
function Pingable {
	case $1 in
		"from")
			filter=" -s $2 "
			desc="$2"
			;;
		"via")
			filter=" -i $2 "
			desc="$2"
			;;
		"always")
			filter=""
			desc="*"
			;;
		*)
			die "Pingable must have arguments ! Please check /etc/adfirewall/manual.txt"
			;;
	esac

	fw-addDescription $PRIO_PINGABLE [input]["$desc"][ping]=ACCEPT
	fw-addRule $PRIO_PINGABLE $IPTABLES -I INPUT -j ACCEPT $filter --protocol icmp
}
